### ISSUE TITLE
Wrong return value of puni-region-balance-p in js2-mode

### ISSUE THREAD

**Issue by DamienCassou** [AmaiKinono/puni#9] opened 2021-09-14 19:46 UTC
Given this content

```js
values
    .filter((a) => a)
    .filter((a) => a);
```
in a `js2-mode` buffer, if I mark the second line and type `M-: (puni-region-balance-p (region-beginning) (region-end)) RET`, I get `nil` but I expect a non-nil value because `.filter((a) => a)` seems balanced to me.

`forward-sexp` seems to work fine but `backward-sexp` goes back  to the beginning of the first line when invoked with point at the end of second line. `forward-sexp-function` is nil.

**Comment by AmaiKinono** [comment] 2021-09-15 06:45
> `forward-sexp-function` is nil.

Could you double check this? It's `js2-mode-forward-sexp` on my side, and if I set it to `nil`, I can't reproduce.

This is because a problem in the `js2-mode-forward-sexp`:

```js
v.f|((a) => a);
// forward-sexp
v.f((a) => a);|
// backward-sexp
|v.f((a) => a);
// forward-sexp
v|.f((a) => a);
```

It treat this line as an sexp when going backward (using `;` as a clue), but doesn't when going forward.

Let me think about how to fix this. I also noticed several other problems in `js2-mode`.

**Comment by DamienCassou** [comment] 2021-09-15 06:50
>> `forward-sexp-function` is nil.
> Could you double check this? It's js2-mode-forward-sexp on my side, and if I set it to nil, I can't reproduce.

you are perfectly right. I don't know what happened but `forward-sexp-function` is indeed equal to `js2-mode-forward-sexp`.

> Let me think about how to fix this. I also noticed several other problems in js2-mode.

thank you very much. Is it something we could fix in `js2-mode` directly so you don't need to add a workaround in `puni`?

**Comment by AmaiKinono** [comment] 2021-09-15 06:53
> Is it something we could fix in `js2-mode` directly so you don't need to add a workaround in `puni`?

I think it is. But to fix improper (in Puni's opinion) handling of sexps is the goal of Puni. If we patch `js2-mode`, we fix this one case. But if we patch Puni, we fix similar problems of other major modes too.

**Comment by DamienCassou** [comment] 2021-09-15 07:27
I agree with you that a general-purpose workaround in Puni can help for other modes. I opened an [issue on the js2-mode project](https://github.com/mooz/js2-mode/issues/574) anyway because they might still want to fix the problem on their side.

**Comment by AmaiKinono** [comment] 2021-09-15 07:45
Should be fixed. Please test.

**Closed** 2021-09-15 07:44 UTC

**Comment by DamienCassou** [comment] 2021-09-15 08:29
Thank you very much
